---
  tasks: 
  - name: update packages
    become: yes
    apt:
      update_cache: yes

  - name: Update all packages to their latest version
    become: yes
    apt:
      name: "*"
      state: latest

  - name: clean up
    become: yes
    apt:
      autoremove: yes

  - name: Check if reboot required
    stat:
      path: /var/run/reboot-required
    register: reboot_required_file

  - name: Reboot if required
    reboot:
    when: reboot_required_file.stat.exists == true
